ARCH=mk
MACHINE=
SCRIPT_NAME=mk
#OUTPUT_ARCH="z80"
OUTPUT_FORMAT="elf32-mk"
MAXPAGESIZE=1
EMBEDDED=yes
TEMPLATE_NAME=elf

TEXT_START_ADDR=0x1000
#TEXT_LENGTH=0
#DATA_ORIGIN=0
#DATA_LENGTH=0
EXTRA_EM_FILE=mk

#FUSE_NAME=fuse

#EEPROM_LENGTH=64K
#FUSE_LENGTH=1K
#LOCK_LENGTH=1K
#SIGNATURE_LENGTH=1K
#USER_SIGNATURE_LENGTH=1K
